### ISSUE TITLE
Julia: vectorized calls

### ISSUE THREAD

**Issue by albop** [EconForge/Dolang#11]
Currently the generated functions don't allow vectorized argument calls. (see below example).
 A very quick fix would be for _unpack_var to return a special type of array view which would implement vectorized views by default. 

@spencerlyon2, I we discussed that when you where in London. Can you remember me which where the options ?

For the record, here is the type of error message one currently gets:

```
type dummytype
end

eqs = [:(1/exp(a)+b)]
args = [(:a,0)]
parms = [:b]

using Dolang

println( make_method(Der{1}, dummytype, eqs, args, parms) )


code = make_method(Der{1}, dummytype, eqs, args, parms, funname=:fun)
f = eval(code)

a = [1.0]
b = [0.0]

f(Der{1},dummytype(),a,b)      # works
f(Der{1},dummytype(),a'',b'')   # doesn't work (a and b are list of points)

```

Here is the output:

```MethodError: Cannot `convert` an object of type Array{Float64,1} to an object of type Float64
This may have arisen from a call to the constructor Float64(...),
since type constructors fall back to convert methods.
 in fun(::Type{Dolang.Der{1}}, ::dummytype, ::Array{Float64,2}, ::Array{Float64,2}) at ./<missing>:0
 in include_string(::String, ::String) at ./loading.jl:441
 in eval(::Module, ::Any) at ./boot.jl:234
 in (::Atom.##60#63)() at /home/pablo/.julia/v0.5/Atom/src/eval.jl:39
 in withpath(::Atom.##60#63, ::Void) at /home/pablo/.julia/v0.5/CodeTools/src/utils.jl:30
 in withpath(::Function, ::Void) at /home/pablo/.julia/v0.5/Atom/src/eval.jl:45
 in macro expansion at /home/pablo/.julia/v0.5/Atom/src/eval.jl:107 [inlined]
 in (::Atom.##59#62)() at ./task.jl:60```

**Comment by spencerlyon2** [comment]
I actually think the new `fun.(args...)` syntax introduce in Julia 0.5 (but available on 0.4 via the `@compat` macro from Compat.jl) should allow us to do this. Check out the "Vectorized function calls" section [here](http://julialang.org/blog/2016/10/julia-0.5-highlights)

Given that I believe this to be the way forward,  I think we can do away completely with the `_unpack_var` function and just assume that all arguments are 1d arrays. It was originally there to extract either a scalar if the first argument (to `_unpack_var`) was a 1d array or a 1d array if the first argument was a 2d array.

**Comment by spencerlyon2** [comment]
Actually, I think I misunderstood something.

the `fun.(...)` syntax is meant to take functions defined over scalars and let them work over arrays.

We have functions defined over 1d arrays and we're asking them to work over >1d arrays. I think we need a bit more brainstorming for this...

**Comment by albop** [comment]
Plus I actually like the unpack - var  function  as we can use it to pass
nothing
