### ISSUE TITLE
make_method call flexibility

### ISSUE THREAD

**Issue by albop** [EconForge/Dolang#20]
The following example work:
```
import Dolang
eqs = [
    :(a*x + b*y)
]
variables = [(:a,0), (:b,0)]
parameters = [:x, :y]
Dolang.make_method(eqs, variables, parameters)
```

Now, two variants of this call don't work yet:

- define group arguments:
    ```
    variables = [ [(:a,0), (:b,0)] ]
    parameters = [:x, :y]
    Dolang.make_method(eqs, variables, parameters)
    ```

- allow arbitrary symbols:
    ```
    eqs = [
        :(a(0)*x + b*y(1))
    ]
    variables = [ (:a,0), :b ]
    parameters = [:x, (:y,1)]
    Dolang.make_method(eqs, variables, parameters)
    ```

Ideally, the make_method would work with any list of symbols which have a normalized string representation. So as soon as we define `(:a,:b,0)` to represent `\frac{\partial a}{\partial b}_t`, we can build and differentiate equations containing derivatives. Same thing for indexed variables.

@sglyon : what do you think prevent us from making these improvements ? For the first issue, we should be fine if we all compound symbols are immutable (i.e. made of tuples). If there is a serious type stability issue, we might want to add a compound symbol object, but I doubt it is required, as they are all normalized as a string symbol anyway. As for the second issue, only reason I can think of is the way we currently deal with definitions.

**Comment by sglyon** [comment]
So for the first case we currently accept things of the form:

```
variables = Dict(X => [(:a, 0), (:b, 0)])
```

I guess because the actual names of the grouped variables (`X` in my example) are mostly used internally, we could automatically generate them if we are given a vector of symbol groups instead of a dict. 

For the second case, I thought we wanted to be very strict about timing, which your example violates in two ways:

- For variables, we always require and explicit time 
- For parameters we only accept time 0, so we can take either `:x` or `(:x, 0)`

**Comment by albop** [comment]
Ah, I know understand the misunderstanding in the second case. That's my fault: I was giving two different meanings to `variables`/`parameters`
I was thinking we could have a `make_method(symbols_to_be_differentiated, constant_symbols)` method, where `symbols_to_be_differentiated` would be a list of arbitrary compound symbols (or a list of list) and constant_symbols a list of compound symbols to be treated as constants.
Btw, I noticed, that `normalize(:x)` is currently the same as `normalize((:x,0))`, but that shouldn't be the case.

**Comment by sglyon** [comment]
We don't have any support for `make_method(symbols_to_be_differentiated, constant_symbols)`

What do you expect each of `normalize(:x)` and `normalize((:x, 0))` to return?

**Comment by albop** [comment]
1/ So let's keep the issue open, as this is a much-needed feature. Way I
thought it was working was by normalizing all input arguments (symbols and
equations), so it seemed to me like a relatively simple extension.
2/ since `normalize( (:a,1) )` produces `_a__1_`, maybe `(:a,0)` ->
`_a__0_' would make sense ?

**Comment by sglyon** [comment]
I'm circling back around to this now.

To be totally honest I  don't see the need for `make_method(symbols_to_be_differentiated, constant_symbols)`. Can help me understand why we need it?

Also I'd be happy to have `normalize((:x, 0))` lower to `_x__0_`. Does that mean the functionality we want is

```
normalize(:x) ==> :_x_
normalize((:x, 0)) ==> :_x__0_
```

?

**Comment by albop** [comment]
Yes for the second part. One shall add the case `normalize(:fun)=>:fun` when fun is a recognized function.

As for the make_method, I need to to be able to make the following calls:
```
make_method([:(a(0)*p+b(0))], [(:a,0),(:b,0)], [:p])
or 
make_method([:(a(0)*p+b(0))], [(:a,0)] ,[(:b,0),:p]) # if I don't need to diff w.r.t. (:b,0)
or
make_method([:(Delta(a,0) + a(0)*p+b(0))], [(:Delta,:a,0), (:a,0)] ,[(:b,0),:p]) # `Delta(a,0) ~ \Delta a_t
or 
make_method([ :( v(0)[0]+ v(0)[1] + v(0)[2] ) ], [(:v,0,0),(:v,0,1),(:v,0,2)] ,[]) # \sum v_{t,i}
```
This was the plan all along (see README file) and these extensions are required by at least three projects outside of dolo (bttt, heterogenous agents, time-consistent modeling).
The only thing that should be required for this to work, is to define the normalized form of the extended symbol (like `Delta(a,0)` represented by `(:Delta,:a,0)`. ) and ensure the `normalize` routine correctly recognizes these type of symbol. `make_method` itself, would just have to normalize the equations, the arguments, and then operate on simple symbols. 
One serious complication to deal with is how to deal with the `definitions` option. Ideally, this should be done outside of the `make_method` method. There would then be an argument `prepend` or smthg, where one could give the resolved definitions.
