### ISSUE TITLE
"Invert" current compiler functions

### ISSUE THREAD

**Issue by sglyon** [EconForge/Dolang#23]
Right now the compiler is implemented in `src/compiler.jl` and is made up of modular chunks of Julia-generating functions that act on an instance of `FunctionFactory`.

@albop and I have discussed and decided that it would be best if made these components act on raw Julia data types (e.g. normalized expressions and variables) instead.  If we have these routines and still wanted to use `FunctionFactory` we could just unpack the relevant fields and send them to the method defined on raw Julia data types.

**Comment by sglyon** [comment]
Hmm, Thinking about this more I am not sure that it is necessary to invert all the internals. It is very convenient to pass a single argument around all these functions.

I think what we should do is make the current `FunctionFactory` (maybe with a new name) just something that will hold the input arguments  (equations, variables, etc.) and helpful data (incidence table) use by the compiler and **not** have it  do things like valuation by default (we could have a `validate` method for this type, but it wouldn't need to happen in the constructor). 

In essence this is an implementation detail that users shouldn't need to know about.

@albop What do you think? Are you ok with the only interface to functions like `signature`, `equation_block`, `body_block`, etc. being through the struct-like type currently named `FunctionFactory`?

**Comment by albop** [comment]
As long as it's for internal consumption and its scope is reduced to hold the intermediate outputs needed by `make_method`, I have no objection and don't really mind the name.

**Comment by sglyon** [comment]
Ok, so I think I'll change the purpose of this issue to be "Make `FunctionFactory` just contain data and not do any validation by default" instead of getting rid of it or inverting all the internals.
