### ISSUE TITLE
Simpler `make_function`  function

### ISSUE THREAD

**Issue by sglyon** [EconForge/Dolang#24]
`make_method` currently does a bit too much (ref #20) and is too hard to use. Let's try to simplify a bit.

Here's one proposal for how to make things more simple:

```
function make_function(
        eqs::Vector{Expr}, variables::AbstractVector,
        to_diff::AbstractVector=1:length(variables);
        dispatch::DataType=Dolang.SkipArg,
        orders::AbstractVector{Int}=[0, 1],
        name::Symbol=:anon, allocating::Bool=true
    )
end
```

The main arguments to this routine are a vector of expressions continuing the equations, a vector of variables, and a vector of integers specifying which variables should be included when constructing derivatives. The only constraint on the `variables` argument is that they need to be things Dolang knows how to `normalize` _into a symbol_ -- that's it. If that constraint is satisfied, then everything is free game.

The output is the _code_ for a function of a single argument `V` that is able to evaluate the equations and requested orders of derivative.

The optional keyword arguments have the following prupose:

- `dispatch`: if a type is passed, the type of the first argument of the generated function will be this type. Note that the actual instance of this type used to dispatch to the function is not used in the function body -- its only purpose is to drive dispatch. If nothing is given, then this argument is not included in the generated code.
- `orders`: Specify the orders of derivative for which a function should be generated
- `name`: The name of the generated function
- `allocating`: Whether or not to generate a version of the function that allocates an array to store the output of the function

Note that a mutating method for the function is _always_ generated.

## Examples

Sorry in advance -- this will be long.

Suppose we are working with the following data

```julia
eqs = [:(a(0)*p+b(0))]
variables = [(:a,0), (:b,0), :p]
to_diff = [1, 2]
```

Then a call to `make_function(e1s, variables, to_diff)` would generate the following Julia code:

```julia
# levels
function anon(V)
    out = Array{eltype(V)}(1)
    anon!(out, V)
end

function anon!(out, V)
    @boundscheck begin
        if size(out) != (1,)
            msg = "Expected out to have 1 element"
            throw(DimensionMismatch(msg))
        end
    end
    _a__0_ = V[1]
    _b__0_ = V[2]
    _p_ = V[3]
    out[1] = _a__0_ * _p_ + _b__0_
    out
end

# first derivative
function anon(::Type{Dolang.Der{1}}, V)
    out = Array{eltype(V)}(1, 2)
    anon!(Der{1}, out, V)
end

function anon!(::Type{Dolang.Der{1}}, out, V)
    @boundscheck begin
        if size(out) != (1, 2)
            msg = "Expected out to have 1 element"
            throw(DimensionMismatch(msg))
        end
    end
    _a__0_ = V[1]
    _b__0_ = V[2]
    _p_ = V[3]
    out[1, 1] =  _p_
    out[1, 2] =  1
    out
end
```

A call to `make_function(e1s, variables, to_diff, name=:myfun) would generate

```julia
# levels
function myfun(V)
    out = Array{eltype(V)}(1)
    myfun!(out, V)
end

function myfun!(out, V)
    @boundscheck begin
        if size(out) != (1,)
            msg = "Expected out to have 1 element"
            throw(DimensionMismatch(msg))
        end
    end
    _a__0_ = V[1]
    _b__0_ = V[2]
    _p_ = V[3]
    out[1] = _a__0_ * _p_ + _b__0_
    out
end

# first derivative
function myfun(::Type{Dolang.Der{1}}, V)
    out = Array{eltype(V)}(1, 2)
    myfun!(Der{1}, out, V)
end

function myfun!(::Type{Dolang.Der{1}}, out, V)
    @boundscheck begin
        if size(out) != (1, 2)
            msg = "Expected out to have 1 element"
            throw(DimensionMismatch(msg))
        end
    end
    _a__0_ = V[1]
    _b__0_ = V[2]
    _p_ = V[3]
    out[1, 1] =  _p_
    out[1, 2] =  1
    out
end
```

A call to `make_function(e1s, variables, to_diff, allocating=false) would generate

```julia
# levels
function anon!(out, V)
    @boundscheck begin
        if size(out) != (1,)
            msg = "Expected out to have 1 element"
            throw(DimensionMismatch(msg))
        end
    end
    _a__0_ = V[1]
    _b__0_ = V[2]
    _p_ = V[3]
    out[1] = _a__0_ * _p_ + _b__0_
    out
end

# first derivative
function anon!(::Type{Dolang.Der{1}}, out, V)
    @boundscheck begin
        if size(out) != (1, 2)
            msg = "Expected out to have 1 element"
            throw(DimensionMismatch(msg))
        end
    end
    _a__0_ = V[1]
    _b__0_ = V[2]
    _p_ = V[3]
    out[1, 1] =  _p_
    out[1, 2] =  1
    out
end
```

A call to `make_function(eqs, variables, to_diff, dispatch=MyType)` (where `MyType` is a known Julia type) would generate

```julia
# levels
function anon(dispatch::MyType, V)
    out = Array{eltype(V)}(1)
    anon!(dispatch, out, V)
end

function anon!(::MyType, out, V)
    @boundscheck begin
        if size(out) != (1,)
            msg = "Expected out to have 1 element"
            throw(DimensionMismatch(msg))
        end
    end
    _a__0_ = V[1]
    _b__0_ = V[2]
    _p_ = V[3]
    out[1] = _a__0_ * _p_ + _b__0_
    out
end

# first derivative
function anon(dispatch::MyType, ::Type{Dolang.Der{1}}, V)
    out = Array{eltype(V)}(1, 2)
    anon!(dispatch, Der{1}, out, V)
end

function anon!(::MyType, ::Type{Dolang.Der{1}}, out, V)
    @boundscheck begin
        if size(out) != (1, 2)
            msg = "Expected out to have 1 element"
            throw(DimensionMismatch(msg))
        end
    end
    _a__0_ = V[1]
    _b__0_ = V[2]
    _p_ = V[3]
    out[1, 1] =  _p_
    out[1, 2] =  1
    out
end
```

This is what I plan on implementing once I've worked through #23 

@albop please let me know if you have any thoughts on this so I can modify the plan as needed.

**Comment by albop** [comment]
One thought: I was thinking about a old feature I wanted at some point. That if vector `m` was useless in the computation of `g(m,s,x,M,p)`, you could actually pass `g(Void,s,x,M,p)` and it would compute things as we expect them.
Now this was feasible in practice the old scheme because you were using some function `index` to get things like `_k_ = index(s,[1])`. I guess this is still feasible if you define a special kind of `V` with a custom indexing function (for instance V actually contains 3 columns but you can overload this index function to get  `index(V,1)=>Void, index(V,2)=>smthg1, index(V,3)=>smthg2, index(V,4)=>smthg3, index(V,5)=>Void`).

**Comment by albop** [comment]
But otherwise, yes I'm happy with that plan. Hopefully the need for the dispatch argument disappears sometime soon.

**Comment by sglyon** [comment]
Hey @albop I'll have to think about how to incorporate your request for being able to pass `nothing` (the singleton instance of `Void`) for any argument that isn't used.

At this stage, the proposal only covers the single argument case, meaning we haven't designed the multi-vector input case. I think that once we work out how we want to do the milt-argument functions we can revisit that request.

So the only reason we have the dispatch argument is so that we can generate multiple "versions" of a function with the same name. Meaning we can have function named `arbitrage`  and use the `dispatch` to customize the behavior for different models. 

An alternative is just to treat the functions as anonymous functions and instead of calling them by name we would store them as variables. For example we could do 

```julia
my_arbitrage = eval(make_method(...))

# call our anonymous funciotn
my_arbitrage(args...)
```

This is how things work when we don't pass anything for dispatch, but doesn't feel very "Julian" (I know -- a loose/vauge concept). 

Providing the dispatch argument still allows us to do this, but also gives us a bit more flexibility. 

How are you thinking about that argument/why would you like to see us get rid of it?

**Comment by sglyon** [comment]
Oh and the actual code would still use the `Dolang._unpack_var` function to retrieve elements of the input arguments, instead of indexing `V` directly. I suppose you can think of the examples above as pseudocode that describes the API and behavior of the `make_function` function, but doesn't show exactly what the implementation of the generated functions looks like.
