### ISSUE TITLE
dolang -> Dolang ?

### ISSUE THREAD

**Issue by albop** [EconForge/Dolang#5]
When doing Pkg.clone("https://github.com/EconForge/dolang") , we get a dolang directory in .julia/vx/ .
But the  module is (rightly) called "Dolang" so that we get `ERROR: LoadError: ArgumentError: Module Dolang not found in current path.`

This would be fixed if we rename the repository to Dolang. Drawback is it wouldn't match the python module, i.e. `dolang`. I wouldn't really mind if we do so, but is there another way ? @spencerlyon2  ?

**Comment by spencerlyon2** [comment]
This is a good question.

Another alternative is to have Dolang.jl and dolang (or dolang.py). That puts a split between the two and might make it harder to keep them together going forward, but it does solve problems like this.

I'm not sure what the right call is for this.

**Comment by albop** [comment]
OK, I just renamed the repository to  `Dolang` . Right now, keeping the two versions in sync is a top priority. In particular, they should use the same functional tests. 
In the future, we might reconsider.
